/* eslint-disable @next/next/no-async-client-component */
import prisma from "@/utils/prisma";
import SettingPageComponent from ".";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: 'პარამეტრები - სამართავი პანელი',
  description: 'Generated by create next app',
}

export default function SettingPage(params: any) {

  return (
    <main className="p-8 ">
      <h1 className="text-3xl mb-6">პარამეტრები</h1>
      <div className="divider"></div>
      <div className="card max-w-md">
        <SettingPageComponent />
      </div>
    </main>
  )
}