import './globals.scss'
import type { Metadata } from 'next'
import { Inter, Open_Sans } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const OpenSans = Open_Sans({subsets: ['cyrillic', 'cyrillic-ext', 'greek', 'vietnamese', 'vietnamese']})
export const dynamicParams = true // true | false,
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
