import type { Metadata } from 'next'
import { Inter, Open_Sans } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const OpenSans = Open_Sans({subsets: ['cyrillic', 'cyrillic-ext', 'greek', 'vietnamese', 'vietnamese']})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='bg-white text-black'>
      <div>{children}</div>
    </div>
  )
}
