import type { Metadata } from 'next'
import DashboardLayout from './layout/index'

export type NavigationItem = {
  icon: string,
  title: string,
  slug: string,
  sub: string[];
}

export const metadata: Metadata = {
  title: 'სამართავი პანელი',
  description: 'Generated by create next app',
}

const DashboardNavigation: NavigationItem[] = [
	{
		icon: 'categoryIcon',
		title: "კატეგორიები",
		slug: "category",
		sub: [],
	},
	{
		icon: "productIcon",
		title: "პროდუქტები",
		slug: "product",
		sub: [],
	},
	{
		icon: "orderIcon",
		title: "შეკვეთები",
		slug: "order",
		sub: [],
	},
];

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {

  function toggleDrawer() {

  }

  return (
    <DashboardLayout navigation={DashboardNavigation}>
      {children}
    </DashboardLayout>
  )
}
