import type { Metadata } from 'next'
import DashboardLayout from './layout/index'

export type NavigationItem = {
  icon: string,
  title: string,
  slug: string,
  sub: string[];
}

// export const metadata: Metadata = {
//   title: 'სამართავი პანელი',
//   description: 'Generated by create next app',
// }

export const DashboardNavigation: NavigationItem[] = [
	{
		icon: 'mainIcon',
		title: "მთავარი",
		slug: "main",
		sub: [],
	},{
		icon: 'categoryIcon',
		title: "კატეგორიები",
		slug: "category",
		sub: [],
	},
	{
		icon: "productIcon",
		title: "პროდუქტები",
		slug: "product",
		sub: [],
	},
	{
		icon: "orderIcon",
		title: "შეკვეთები",
		slug: "order",
		sub: [],
	},
  {
		icon: "settingIcon",
		title: "პარამეტრები",
		slug: "setting",
		sub: [],
	}
];

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {

  function toggleDrawer() {

  }

  return (
    <DashboardLayout navigation={DashboardNavigation}>
      {children}
    </DashboardLayout>
  )
}
