import type { Metadata } from 'next'
import DashboardLayout from './layout/index'

export const metadata: Metadata = {
  title: 'სამართავი პანელი',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {

  function toggleDrawer() {

  }

  return (
    <DashboardLayout>
      {children}
    </DashboardLayout>
  )
}
