import Image from "next/image";
import { DashboardNavigation } from "./layout";
import DashboardMainComponent from "./index";
import prisma from '@/utils/prisma';
import { getServerSession } from "next-auth";
import { useRouter } from "next/router";
import { redirect } from "next/navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'მთავარი - სამართავი პანელი',
  description: 'Generated by create next app',
}

export default async function Home() {
  
  const counts =  {
    category: await prisma.categorie.count(),
    product: await prisma.product.count(),
    order: await prisma.order.count(),
  }

  return <DashboardMainComponent counts={counts} />;
}
