import prisma from "../../../utils/prisma";
import { OrderPage } from ".";
import { Metadata } from "next";

export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
  title: 'შეკვეთები - სამართავი პანელი',
  description: 'Generated by create next app',
}

export default async function Home() {
	const listData = await prisma.order
		.findMany({
			include: {
        cityRegion: {
          select: {
            name: true
          }
        },
				product: {
          include: {
            categories: true
          }
        },
			},
      orderBy: {
        createdAt: 'desc'
      }
		})
		.then((r) => {
			return r;
		})
		.catch((e) => {
			return [];
		});


	return (
		<main>
			<OrderPage list={listData} />
		</main>
	);
}
